matrix:
  include:
    - language: scala
      scala: 2.12.3
      before_script:
        - cd atcoder-problems
      script:
        - sbt clean coverage test coverageReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
